import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import styles from "./Home.module.scss";
import Header from "components/Header";
import MainVisual from "components/MainVisual";
import ProfileSection from "components/ProfileSection";
import YouTubeSection from "components/YouTubeSection";
import WorkSection from "components/WorkSection";
import BlogSection from "components/BlogSection";
import ContactSection from "components/ContactSection";
import Footer from "components/Footer";
import { BlogData, PortfolioData, YoutubeData } from "types/api";
import { MicroCMSContents } from "types/microcms";
import { fetcher } from "utils/fetcher";

export type HomeProps = {
  blogData: MicroCMSContents<BlogData>;
  portfolioData: MicroCMSContents<PortfolioData>;
  youtubeData: MicroCMSContents<YoutubeData>;
};
const Home: NextPage<HomeProps> = ({
  blogData,
  portfolioData,
  youtubeData,
}) => {
  return (
    <div className={styles.root}>
      <Head>
        <title>三波ヨタ|オフィシャルサイト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <MainVisual />
        <ProfileSection />
        <YouTubeSection data={youtubeData.contents} />
        <WorkSection data={portfolioData.contents} />
        <BlogSection data={blogData.contents} />
        <ContactSection />
      </main>
      <Footer />
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const blogData = await fetcher("/blog", 3);
  const portfolioData = await fetcher("/works", 3);
  const youtubeData = await fetcher("/youtube", 6);

  return {
    props: { blogData, portfolioData, youtubeData },
  };
};

export default Home;
