name: Vercel Deploy CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run yarn install
        run: yarn install
      - name: node version
        run: node -v
      - name: Run tests
        run: yarn test
